baseURL = "https://studio-nugget.github.io/blog/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Studio Nugget Devlog"
theme = "cupper-hugo-theme"
publishDir = "docs"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Studio Nugget is a four-person game studio working on a game about the Polish Resistance during WW2."
  homeMetaContent = "Studio Nugget is a small game dev studio comprised of four students."
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"

[menu]
  [[menu.nav]]
    name = "Devlog"
    url = "/posts/"
    weight = 1